Traceback (most recent call last):
  File "/deac/csc/khuriGrp/zhaok220/clustering_2/scripts/test_kidney.py", line 3, in <module>
    from clusterer import *
  File "/deac/csc/khuriGrp/zhaok220/clustering_2/scripts/clusterer.py", line 17, in <module>
    with open('./ga_parameters.yaml') as file:
FileNotFoundError: [Errno 2] No such file or directory: './ga_parameters.yaml'
